# Generated by Django 5.0.7 on 2024-09-18 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='strip_id',
            new_name='stripe_id',
        ),
    ]
