# Generated by Django 5.0.7 on 2024-10-10 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0013_alter_subscriptionprice_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='features',
            field=models.TimeField(blank=True, help_text='Features for pricing, separated by new line', null=True),
        ),
    ]
