# Generated by Django 5.0.7 on 2024-10-10 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0015_alter_subscription_features'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='features',
        ),
    ]
