# Generated by Django 5.0.7 on 2024-10-11 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0017_subscription_features'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='subtitle',
            field=models.CharField(blank=True, null=True),
        ),
    ]
